### ISSUE TITLE
Update javax.media artifacts for Java 9 compatibility

### ISSUE THREAD

**Issue by don-vip** [geosolutions-it/jai-ext#161]
This project currently depends on following artifacts:

```
javax.media:jai_core:1.1.3
javax.media:jai_codec:1.1.3
javax.media:jai_imageio:1.1
```

which are outdated and not compatible with Java 9 new version scheme, as it causes the following error:
```
java.lang.NumberFormatException: For input string: ""
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.base/java.lang.Integer.parseInt(Integer.java:662)
	at java.base/java.lang.Integer.parseInt(Integer.java:770)
	at com.sun.media.imageioimpl.common.ImageUtil.processOnRegistration(ImageUtil.java:1408)
	at com.sun.media.imageioimpl.plugins.wbmp.WBMPImageWriterSpi.onRegistration(WBMPImageWriterSpi.java:106)
	at java.desktop/javax.imageio.spi.SubRegistry.registerServiceProvider(ServiceRegistry.java:788)
	at java.desktop/javax.imageio.spi.ServiceRegistry.registerServiceProvider(ServiceRegistry.java:330)
```

See following related issues:
- https://github.com/jai-imageio/jai-imageio-core/issues/24
- https://bugs.openjdk.java.net/browse/JDK-8154860

**Comment by aaime** [comment]
The JDK behavior was apparently work-arounded and the ticket solved, but I'm still seeing exactly the same stack trace. About upgrading, I'm not sure what you're suggesting here? 
It seems we'd have to fork all those packages and "fix them" somehow, since all the code in jai-ext is built on top of them (and from here we go to GeoTools and GeoServer).

**Comment by aaime** [comment]
Actually tested on a Oracle JDK 9 release, JAI-EXT builds fine (with tests, so I assume it's working) although I'm seeing in the build a lot of these:

{code}
Caught and handled this exception :
java.lang.NumberFormatException: For input string: ""
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.base/java.lang.Integer.parseInt(Integer.java:662)
	at java.base/java.lang.Integer.parseInt(Integer.java:770)
	at com.sun.media.imageioimpl.common.ImageUtil.processOnRegistration(ImageUtil.java:1408)
	at com.sun.media.imageioimpl.plugins.wbmp.WBMPImageReaderSpi.onRegistration(WBMPImageReaderSpi.java:95)
	at java.desktop/javax.imageio.spi.SubRegistry.registerServiceProvider(ServiceRegistry.java:788)
	at java.desktop/javax.imageio.spi.ServiceRegistry.registerServiceProvider(ServiceRegistry.java:330)
	at java.desktop/javax.imageio.spi.IIORegistry.registerApplicationClasspathSpis(IIORegistry.java:212)
	at java.desktop/javax.imageio.spi.IIORegistry.<init>(IIORegistry.java:136)
	at java.desktop/javax.imageio.spi.IIORegistry.getDefaultInstance(IIORegistry.java:157)
	at java.desktop/javax.imageio.ImageIO.<clinit>(ImageIO.java:66)
	at com.sun.media.jai.imageioimpl.ImageReadCRIF.getImageInputStream(ImageReadCRIF.java:168)
	at com.sun.media.jai.imageioimpl.ImageReadCRIF.getImageReader(ImageReadCRIF.java:189)
	at com.sun.media.jai.imageioimpl.ImageReadCRIF.create(ImageReadCRIF.java:277)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at javax.media.jai.FactoryCache.invoke(FactoryCache.java:122)
	at javax.media.jai.OperationRegistry.invokeFactory(OperationRegistry.java:1674)
	at it.geosolutions.jaiext.ConcurrentOperationRegistry.invokeFactory(ConcurrentOperationRegistry.java:576)
	at javax.media.jai.registry.RIFRegistry.create(RIFRegistry.java:332)
	at javax.media.jai.RenderedOp.createInstance(RenderedOp.java:819)
{code}

As you say an update in imageio would be needed, but that would require a fork of it... maybe a light one, just un-registering the WMPB format, which is of no particular interest.

**Comment by don-vip** [comment]
This is not limited to WBMP. The bug is in "common" part of JAI, so the following plugins do not work:
- WBMP
- BMP
- GIF
See https://github.com/jai-imageio/jai-imageio-core/issues/24#issuecomment-225751170 for a proposed fix.

**Comment by aaime** [comment]
Hmm... they could all be removed from an eventual re-packaging of imageio, GIF and BMP are part of the JDK already. That community fork of imageio does not seem all that alive to me? :-)

**Comment by don-vip** [comment]
Your call. I don't even know why we need JAI in the first place. It's just annoying to see all these error messages when we run GeoTools on Java 9.

**Comment by aaime** [comment]
The project is called JAI-ext... as an extension on top of JAI. All the API and basic functionality is provided by Java Advanced Imaging, this project is a set of re-implementations of certain pluggable operators to fix bugs or provide extra functionality.

Without JAI it would not even exist. There are discussions around to do a full re-implementation of JAI from scratch, but well, that's going to be a massive project if it ever happens.

**Comment by don-vip** [comment]
I see [replacing JAI](https://github.com/geotools/geotools/wiki/Replace-JAI) is the [only project asking for budget](https://github.com/geotools/geotools/wiki/GeoTools-Budget-Request-2018), so there are good chances see the replacement interfaces next year? If the project is really going to happen, as far as I'm concerned, don't bother to fix these warnings, I prefer to see efforts spent on the replacement library :)

**Comment by don-vip** [comment]
Hello,
I see in "GeoTools / GeoServer Meeting 2018-01-09" minutes the work on Replacing JAI is cancelled? :(
So this issue should be fixed, there are other bug reports such as https://osgeo-org.atlassian.net/browse/GEOT-5914

**Comment by abrin** [comment]
FYI, less than helpful, but this [comment](https://github.com/medusa-project/cantaloupe/issues/176#issuecomment-381998096) suggests that it may be worth looking at Java10 which doesn't have this error (though it may have other issues)

**Comment by aaime** [comment]
@abrin actually helpful in my opinion, jdk 9 and 10 are simple throway releases that we are not concerned about (besides using them as "training tools"), the whole GeoTools/GeoServer ecosystem is only going to target LTS releases supported by https://adoptopenjdk.net/ (Oracle will provide LTS treatment only to show paying anyways, there will be no more free LTSs from them).

I'll give JDK 10 a spin and run a build on it.
