### ISSUE TITLE
Upgrade to jts-core 1.14

### ISSUE THREAD

**Issue by jodygarnett** [geosolutions-it/jai-ext#162]
In upgrading to jts-core-1.14 I have the following incompatibility:

```
Exception in thread "SunTileScheduler0Standard1" java.lang.NoClassDefFoundError: com/vividsolutions/jtsexample/geom/ExtendedCoordinate
	at it.geosolutions.jaiext.vectorbin.VectorBinarizeOpImage.getTestRect(VectorBinarizeOpImage.java:275)
	at it.geosolutions.jaiext.vectorbin.VectorBinarizeOpImage.getTileRaster(VectorBinarizeOpImage.java:155)
	at it.geosolutions.jaiext.vectorbin.VectorBinarizeOpImage.computeTile(VectorBinarizeOpImage.java:137)
	at com.sun.media.jai.util.SunTileScheduler.scheduleTile(SunTileScheduler.java:904)
	at javax.media.jai.OpImage.getTile(OpImage.java:1129)
	at javax.media.jai.PlanarImage.getData(PlanarImage.java:2085)
	at javax.media.jai.RenderedOp.getData(RenderedOp.java:2276)
	at it.geosolutions.jaiext.mosaic.MosaicOpImage.computeTile(MosaicOpImage.java:912)
	at com.sun.media.jai.util.SunTileScheduler.scheduleTile(SunTileScheduler.java:904)
	at javax.media.jai.OpImage.getTile(OpImage.java:1129)
	at com.sun.media.jai.util.SunTileScheduler.compute(SunTileScheduler.java:717)
	at com.sun.media.jai.util.TileJob.compute(SunTileScheduler.java:373)
	at com.sun.media.jai.util.WorkerThread.run(SunTileScheduler.java:468)
```

I had understood the contents of jts-example to be just that ... example code.

With this in mind the dependency change is:

```
      <dependency>
        <groupId>com.vividsolutions</groupId>
        <artifactId>jts-core</artifactId>
        <version>1.14.0</version>
      </dependency>
      <dependency>
        <groupId>com.vividsolutions</groupId>
        <artifactId>jts-example</artifactId>
        <version>1.14.0</version>
      </dependency>
```

**Comment by jodygarnett** [comment]
Note jts has a transitive dependency on xerces via jai-ext necesitating the need for:

```
  <dependency>
      <groupId>it.geosolutions.jaiext.affine</groupId>
      <artifactId>jt-affine</artifactId>
      <exclusions>
         <exclusion>
            <groupId>com.vividsolutions</groupId>
            <artifactId>jts</artifactId>
         </exclusion>
      </exclusions>
  </dependency>
```
