### ISSUE TITLE
Bicubic warp fails with 

### ISSUE THREAD

**Issue by aaime** [geosolutions-it/jai-ext#72]
The bicubic warp end up accessing past the end of an array (could not reproduce the same issue

````
giu 01, 2015 12:08:33 PM org.geoserver.GeoserverInitStartupListener$1 errorOccurred
INFORMAZIONI: Problem occurs when computing a tile by the owner.
java.lang.ArrayIndexOutOfBoundsException: 1024
	at it.geosolutions.jaiext.warp.WarpBicubicOpImage.bicubicCalculationInt(WarpBicubicOpImage.java:3122)
	at it.geosolutions.jaiext.warp.WarpBicubicOpImage.computeRectByte(WarpBicubicOpImage.java:260)
	at it.geosolutions.jaiext.warp.WarpOpImage.computeRect(WarpOpImage.java:285)
	at it.geosolutions.jaiext.warp.WarpOpImage.computeTile(WarpOpImage.java:232)
	at com.sun.media.jai.util.SunTileScheduler.scheduleTile(SunTileScheduler.java:904)
	at javax.media.jai.OpImage.getTile(OpImage.java:1129)
	at it.geosolutions.jaiext.crop.CropOpImage.getTile(CropOpImage.java:77)
	at it.geosolutions.jaiext.border.BorderOpImage.copyRasterData(BorderOpImage.java:359)
	at it.geosolutions.jaiext.border.BorderOpImage.computeTile(BorderOpImage.java:281)
	at com.sun.media.jai.util.SunTileScheduler.scheduleTile(SunTileScheduler.java:904)
	at javax.media.jai.OpImage.getTile(OpImage.java:1129)
	at javax.media.jai.PlanarImage.cobbleByte(PlanarImage.java:2850)
	at javax.media.jai.PlanarImage.getData(PlanarImage.java:2169)
	at javax.media.jai.RenderedOp.getData(RenderedOp.java:2276)
````

The failing request is "http://localhost:8080/geoserver/wms?LAYERS=ne_mosaic&FORMAT=image%2Fjpeg&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&STYLES=&SRS=EPSG%3A54029&BBOX=0.0000042468309402466,-20037508.342789,20037508.342797,0.0000042468309402466&WIDTH=256&HEIGHT=256" against a mosaic derived from naturalearth by applying gdal_retile (does not happen on the original image).

The mosaic.properties, for quick reference, is here:
``
#-Automagically created from GeoTools-
#Thu May 28 10:55:32 GMT 2015
Levels=0.01666666666667,0.01666666666667 0.03333333333334,0.03333333333334 0.06666666666668,0.06666666666668 0.13333333333336,0.13333333333336 0.26666666666672,0.26666666666672 0.53333333333344,0.53333333333344 1.06666666666688,1.06666666666688
Heterogeneous=true
AbsolutePath=false
Name=ne_mosaic
TypeName=ne_mosaic
Caching=false
ExpandToRGB=false
LocationAttribute=location
SuggestedSPI=it.geosolutions.imageioimpl.plugins.tiff.TIFFImageReaderSpi
CheckAuxiliaryMetadata=false
LevelsNum=7
``
I can provide the full mosaic, but it's almost a GB large.

Looking at the code, I have the impression the custom "floor" method might be the cause, we have:

``
final float sx = warpData[count++];
                        final float sy = warpData[count++];

                        final int xint = floor(sx);
                        final int yint = floor(sy);
                        final float xfrac = sx - xint;
                        final float yfrac = sy - yint;
``

sy is exaclty -1, floor done as is makes it -2, and yfrac becomes 1, while I have the impression the value is meant to be in [0,1[

The definition of WarpOpImage.floor looks at least fishy:

````
public static final int floor(final float f) {
        return f >= 0 ? (int) f : (int) f - 1;
````

**Comment by spyhunter99** [comment]
related ticket #93
