### ISSUE TITLE
consider NoDataContainer `float` methods for those that take `double`

### ISSUE THREAD

**Issue by tkunicki** [geosolutions-it/jai-ext#92]
I was debugging some performance regressions when processing float[] images with multiple threads.  A thread dump exposed a number of thread blocked attempting to log.

```
   java.lang.Thread.State: BLOCKED (on object monitor)
	at java.util.logging.StreamHandler.publish(StreamHandler.java:206)
	- waiting to lock <0x0000000748638348> (a java.util.logging.ConsoleHandler)
	at java.util.logging.ConsoleHandler.publish(ConsoleHandler.java:116)
	at java.util.logging.Logger.log(Logger.java:738)
	at java.util.logging.Logger.doLog(Logger.java:765)
	at java.util.logging.Logger.log(Logger.java:788)
	at it.geosolutions.jaiext.range.Range.containsN(Range.java:145)
	at it.geosolutions.jaiext.range.Range.contains(Range.java:129)
	at it.geosolutions.jaiext.warp.WarpNearestOpImage.computeRectFloat(WarpNearestOpImage.java:994)
```

For some reason in `Range.computeN(...), L145` logging was attempted on each value check.
```
        if (LOGGER.isLoggable(Level.FINE)) {
            LOGGER.log(Level.FINE, "Wrong data type tested: Input: " + value.getClass()
                    + ", output: " + this.getDataType().getClassValue());
        }
```
 I don't have `juli` logging levels explicitly set so why my test driver was attempting to log at `FINE` is an issue for me to address independently.  *But* from looking at the flow through `computeN` it appears it advantageous for perfomance that one's `Range` instances match the type being processed.  

With `float` data types `NaN` is a common NoData flag.  I was previously using `new NoDataContainer(Float.NaN).getAsRange()` for ` DataBuffer.TYPE_FLOAT` configured interpolators.  I hadn't studied the interface and it's now obvious that `NoDataContainer` only takes `double` arguments for primitives.

I've resolved my issue with the following, but this might not be obvious to future users:
```
RangeFactory.convertToFloatRange(NoDataContainer(Float.NaN).getAsRange())
```

**Comment by aaime** [comment]
Hi Tom, in 1.0.6 I tried to cast all nodata ranges coming into jaitools operators to the type of the images being processed... are you still using 1.0.5 or did I miss stuff?

**Comment by tkunicki** [comment]
Hi, Andrea.

I am using 1.0.6 as it's the listed dependency for geotools 14-RC1.

This is more of a documentation/usability issue.  I created a `NoDataContainer` instance using Float.NaN for my float[] data but the `Range` instances `NoDataContainer` generates are `Range<Double>` (there aren't `float` methods and given the widening cast, no warnings from IDE or compiler).  I hadn't noticed this as an issue until from some reason _some_ of my tests were running ~100x slower.
